version: '3.1'

services:
  app:
    container_name: web-52-shop
    build:
      context: .
      dockerfile: ./dockerfiles/dev.dockerfile
    ports:
      - ${PORT}:3000
    volumes:
      - ./src:/app/src
      - ./public:/app/public
      - ./prisma:/app/prisma
    restart: always
    depends_on:
      - postgres
    networks:
      - web_52_shop

  postgres:
    image: postgres:14.5
    container_name: db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_BASE}
    ports:
      - ${DB_PORT}:5432
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data
    networks:
      - web_52_shop

networks:
  web_52_shop:
    name: web_52_shop_network